[[redirects]]
  from = "http://torvenindustries.com/*"
  to = "https://torvenindustries.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"