[[redirects]]
  from = "http://torven.web.id/*"
  to = "https://torven.web.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"